"""initial_schema

Revision ID: 77d1e7b8e390
Revises:
Create Date: 2026-03-04 13:57:32.016731

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "77d1e7b8e390"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
